### ISSUE TITLE
Uses  import * from before it defines it

### ISSUE THREAD

**Issue by rossmawd** [learn-co-curriculum/react-modular-code#12]
import * from

use before definition

**Comment by maxwellbenton** [comment]
Hi @rossmawd,

Thank you for spotting this and providing feedback. We've updated the text around the first example of `import *` to briefly introduce it. The way this lesson is set up, in order for the export example to work, `import *` is needed. Otherwise, the code would be invalid. To resolve this, we've added a brief explanation of what `import *` is doing in this section, which should resolve this issue.

Thank you for contributing and helping to improve our curriculum for future students!
